import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "next.js coding",
    template: "%s | coding",
    absolute: ""
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
